import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"

const integralcf = localFont({
  src: [
    { path: "/fonts/IntegralCF-Regular.woff2", weight: "400", style: "normal" },
    { path: "/fonts/IntegralCF-Bold.woff2", weight: "700", style: "normal" },
  ]
})

const satoshi = localFont({
  src: [
    { path: "/fonts/Satoshi-Regular.woff2", weight: "400", style: "normal" },
    { path: "/fonts//Satoshi-Bold.woff2", weight: "700", style: "normal" },
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${integralcf.className} ${satoshi.className}`}>{children}</body>
    </html>
  )
}
